/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-2",
    "aws_appsync_graphqlEndpoint": "https://4ruq4uofsnf2pcjt4j3qmeurcm.appsync-api.us-east-2.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-2",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-gkglzfy2tvcsjlcbbd7b37454a",
    "aws_cognito_identity_pool_id": "us-east-2:84b73bce-b01e-4183-a789-d928f0560850",
    "aws_cognito_region": "us-east-2",
    "aws_user_pools_id": "us-east-2_xDSXue8xN",
    "aws_user_pools_web_client_id": "68dii8lk9a7gi1vvuk432riovs",
    "oauth": {}
};


export default awsmobile;
